[tasks.build_image]
category = "develop"
description = "Build neovim-container image"
script = [
    '''
    uid=$(id -u "$(whoami)")
    docker build -t mijinko17/neovim-container-uid-"$uid":develop --network host --build-arg uid="$uid" .
    ''',
]

[tasks.build_rust]
category = "develop"
description = "Build rust"
command = "cargo"
args = ["build", "--features", "develop"]

[tasks.build_all]
category = "develop"
description = "Build image and rust"
dependencies = ["build_image", "build_rust"]

[tasks.run]
category = "develop"
description = "Run binary"
command = "cargo"
args = ["run", "--features", "develop"]

[tasks.build_and_run]
category = "develop"
description = "Run binary"
dependencies = ["build_image", "run"]

[tasks.format_check]
description = "Check code format."
category = "develop"
command = "cargo"
args = ["fmt", "--check"]

[tasks.lint]
description = "Run linter"
category = "develop"
command = "cargo"
args = ["check"]

[tasks.test]
description = "Run all tests."
category = "develop"
command = "cargo"
args = ["test"]

[tasks.ci]
description = "ci"
category = "develop"
dependencies = ["format_check", "lint", "test"]
