[tasks.build_image]
category = "develop"
description = "Build neovim-container image"
script = [
    '''
    uid=$(id -u "$(whoami)")
    docker build -t mijinko17/neovim-container-uid-"$uid":develop --network host --build-arg uid="$uid" .
    ''',
]

[tasks.build_rust]
category = "develop"
description = "Build rust"
dependencies = ["build"]

[tasks.build_all]
category = "develop"
description = "Build image and rust"
dependencies = ["build_image", "build_rust"]

[tasks.run]
category = "develop"
description = "Run binary"
script = ['''
cargo run
''']

[tasks.build_and_run]
category = "develop"
description = "Run binary"
dependencies = ["build_image", "run"]
